### ISSUE TITLE
Example for function linear-model throws NPE

### ISSUE THREAD

**Issue by behrica** [incanter/incanter#283] opened 2015-01-02 22:33 UTC
This example code for function linear-model throws a NPE in incanter 1.9.0

````clojure
 (use '(incanter core stats datasets charts))
 (def iris (to-matrix (get-dataset :iris) :dummies true))
 (def y (sel iris :cols 0))
 (def x (sel iris :cols (range 1 6)))
 (def iris-lm (linear-model y x)) ; throws NPE
````

**Comment by behrica** [comment] 2015-01-02 23:00
I debugged it a bit and the root cause is taht (nrow y) returns nil.

So the following is teh minmal test case to reproduce teh problem:

````clojure
 (use '(incanter core stats datasets charts))
 (def iris (to-matrix (get-dataset :iris) :dummies true))
 (def y (sel iris :cols 0))
(nrow y) -> returns nil 
```

It returns nil, as the class of y is mikera.vectorz.Vector, which is neither a matrix? nor a dataset? nor a coll?.

**Comment by behrica** [comment] 2015-01-02 23:18
By converting x and y to matrix of type :persistent-vector it works.

````clojure
(use '(incanter core stats datasets charts))
(require '[clojure.core.matrix :as m])
 (def iris  (to-matrix (get-dataset :iris) :dummies true))
 (def y (sel iris :cols 0))
 (def x (sel iris :cols (range 1 6)))
(def y1 (m/matrix :persistent-vector y))
(def x1 (m/matrix :persistent-vector x))
 (def iris-lm (linear-model y1 x1))
````

**Comment by behrica** [comment] 2015-01-02 23:20
I was already surprised to see that "by default" clj-vectorz gets choosen.
I thought that it is a 3rd party matrix implementation which needs to be added and choosen explicitely.

**Comment by mikera** [comment] 2015-01-03 04:07
The question of what implementation gets used by default is interesting. Previously it was Clatrix (which has native dependencies, so often inconvenient in many environments). We could default to using no implementation (just persistent vectors etc.) but that is slow for many operations. vectorz-clj is pure JVM code and pretty fast, though  it is currently limited to `double` maths. Not sure what the best solution is....

**Comment by Gerrrr** [comment] 2015-01-28 16:06
Thank you for the catch!
The issue is fixed in development branch.

**Closed** 2015-09-13 18:53 UTC
